import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { exportDocx, exportPdf, type ExportDocumentKind } from "@/lib/documentExport";
import { ArrowLeft, CalendarClock, Clipboard, Download, FileDown, FileText, Sparkles } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { toast } from "sonner";

const statuses = [["to-apply", "To apply"], ["applied", "Applied"], ["interview", "Interview"], ["offer", "Offer"], ["rejected", "Rejected"]] as const;
type WorkspaceForm = { company: string; role: string; jobDescription: string; contextMode: "full" | "limited"; contactEmail: string; sourceUrl: string; status: string; notes: string; tailoredResume: string; emailDraft: string; nextAction: string; followUpAt: string };
const emptyForm: WorkspaceForm = { company: "", role: "", jobDescription: "", contextMode: "full", contactEmail: "", sourceUrl: "", status: "to-apply", notes: "", tailoredResume: "", emailDraft: "", nextAction: "", followUpAt: "" };

function dateInput(value: Date | null) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }
function copyText(value: string, label: string) { void navigator.clipboard.writeText(value).then(() => toast.success(`${label} copied.`)).catch(() => toast.error("Copy was unavailable. Please select the text manually.")); }
function downloadText(value: string, filename: string) { const url = URL.createObjectURL(new Blob([value], { type: "text/plain;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

function ExportActions({ content, kind, fileStem, company, role }: { content: string; kind: ExportDocumentKind; fileStem: string; company: string; role: string }) {
  const label = kind === "resume" ? "Resume" : "Cover letter";
  const disabled = !content.trim();
  const input = { content, kind, fileStem, company, role };
  async function createDocx() {
    try { await exportDocx(input); toast.success(`${label} DOCX downloaded.`); } catch { toast.error(`Could not create the ${label.toLowerCase()} DOCX.`); }
  }
  function createPdf() {
    try { exportPdf(input); toast.success(`${label} PDF downloaded.`); } catch { toast.error(`Could not create the ${label.toLowerCase()} PDF.`); }
  }
  return <div className="flex flex-wrap gap-1"><Button type="button" size="sm" variant="ghost" disabled={disabled} onClick={() => copyText(content, label)}><Clipboard className="mr-1.5 h-3.5 w-3.5" />Copy</Button><Button type="button" size="sm" variant="ghost" disabled={disabled} onClick={() => downloadText(content, `${fileStem}-${kind}.txt`)}><Download className="mr-1.5 h-3.5 w-3.5" />Text</Button><Button type="button" size="sm" variant="outline" className="bg-background" disabled={disabled} onClick={() => void createDocx()}><FileText className="mr-1.5 h-3.5 w-3.5" />DOCX</Button><Button type="button" size="sm" variant="outline" className="bg-background" disabled={disabled} onClick={createPdf}><FileDown className="mr-1.5 h-3.5 w-3.5" />PDF</Button></div>;
}

export default function JobWorkspace() {
  const [, params] = useRoute("/jobs/:id");
  const jobId = Number(params?.id);
  const utils = trpc.useUtils();
  const { data: job, isLoading } = trpc.jobs.get.useQuery({ id: jobId }, { enabled: Number.isFinite(jobId) });
  const [form, setForm] = useState<WorkspaceForm>(emptyForm);
  useEffect(() => { if (job) setForm({ company: job.company, role: job.role, jobDescription: job.jobDescription, contextMode: job.contextMode, contactEmail: job.contactEmail ?? "", sourceUrl: job.sourceUrl ?? "", status: job.status, notes: job.notes ?? "", tailoredResume: job.tailoredResume ?? "", emailDraft: job.emailDraft ?? "", nextAction: job.nextAction ?? "", followUpAt: dateInput(job.followUpAt) }); }, [job]);
  const save = trpc.jobs.update.useMutation({ onSuccess: data => { if (data) setForm({ company: data.company, role: data.role, jobDescription: data.jobDescription, contextMode: data.contextMode, contactEmail: data.contactEmail ?? "", sourceUrl: data.sourceUrl ?? "", status: data.status, notes: data.notes ?? "", tailoredResume: data.tailoredResume ?? "", emailDraft: data.emailDraft ?? "", nextAction: data.nextAction ?? "", followUpAt: dateInput(data.followUpAt) }); toast.success("Workspace saved."); void utils.jobs.list.invalidate(); }, onError: error => toast.error(error.message) });
  const generate = trpc.jobs.generateDrafts.useMutation({ onSuccess: data => { if (data) setForm(current => ({ ...current, tailoredResume: data.tailoredResume ?? "", emailDraft: data.emailDraft ?? "" })); toast.success(form.contextMode === "limited" ? "Factual outreach email ready. Your master resume was left unchanged." : "Grounded drafts are ready to review."); void utils.jobs.list.invalidate(); }, onError: error => toast.error(error.message) });
  function submit(event: FormEvent) { event.preventDefault(); save.mutate({ id: jobId, ...form, contactEmail: form.contactEmail || null, sourceUrl: form.sourceUrl || null, status: form.status as typeof statuses[number][0], nextAction: form.nextAction || null, followUpAt: form.followUpAt || null }); }
  if (isLoading) return <div className="mx-auto max-w-6xl space-y-5"><div className="h-12 w-48 animate-pulse rounded bg-muted" /><div className="h-96 animate-pulse rounded-[1.5rem] border bg-card" /></div>;
  if (!job) return <div className="mx-auto max-w-2xl rounded-2xl border bg-card p-8"><h1 className="editorial-title text-4xl">Application unavailable</h1><p className="mt-3 text-muted-foreground">This workspace cannot be found in your personal pipeline.</p><Button asChild className="mt-6"><Link href="/"><ArrowLeft className="mr-2 h-4 w-4" />Back to applications</Link></Button></div>;
  const fileStem = `${form.company}-${form.role}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return <form onSubmit={submit} className="mx-auto max-w-7xl space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><Button asChild variant="ghost" className="w-fit px-0 text-muted-foreground hover:bg-transparent hover:text-foreground"><Link href="/"><ArrowLeft className="mr-2 h-4 w-4" />All applications</Link></Button><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" className="bg-card" onClick={() => generate.mutate({ id: jobId })} disabled={generate.isPending}><Sparkles className="mr-2 h-4 w-4" />{generate.isPending ? "Creating draft…" : form.contextMode === "limited" ? "Refresh factual outreach" : "Refresh tailored drafts"}</Button><Button type="submit" disabled={save.isPending}>{save.isPending ? "Saving…" : "Save changes"}</Button></div></div>
  <section className="rounded-[1.6rem] border bg-[radial-gradient(circle_at_85%_15%,oklch(0.9_0.06_70),transparent_26%),linear-gradient(135deg,oklch(0.995_0.005_80),oklch(0.955_0.015_76))] p-6 sm:p-8 dark:bg-[radial-gradient(circle_at_85%_15%,oklch(0.34_0.07_55),transparent_28%),linear-gradient(135deg,oklch(0.18_0.022_40),oklch(0.22_0.026_42))]"><p className="data-label text-primary">Application workspace</p><div className="mt-3 grid gap-4 lg:grid-cols-[1fr_1fr_auto]"><div className="space-y-2"><Label htmlFor="company">Company</Label><Input id="company" value={form.company} onChange={event => setForm({ ...form, company: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="role">Role</Label><Input id="role" value={form.role} onChange={event => setForm({ ...form, role: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="status">Status</Label><select id="status" className="h-10 min-w-32 rounded-md border bg-background px-3 text-sm" value={form.status} onChange={event => setForm({ ...form, status: event.target.value })}>{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div></section>
  <div className="grid gap-6 xl:grid-cols-[0.82fr_1.18fr]"><div className="space-y-6"><section className="paper-panel rounded-[1.4rem] border p-5"><div className="flex items-center gap-2"><CalendarClock className="h-4 w-4 text-primary" /><p className="data-label text-primary">Action tracker</p></div><h2 className="editorial-title mt-2 text-3xl">Keep the next move clear</h2><div className="mt-5 space-y-4"><div className="space-y-2"><Label htmlFor="next-action">Next action</Label><Input id="next-action" value={form.nextAction} onChange={event => setForm({ ...form, nextAction: event.target.value })} placeholder="Send a follow-up, prepare for a screen, or review the role…" /></div><div className="space-y-2"><Label htmlFor="workspace-follow-up">Follow-up date</Label><Input id="workspace-follow-up" type="date" value={form.followUpAt} onChange={event => setForm({ ...form, followUpAt: event.target.value })} /></div></div></section><section className="paper-panel rounded-[1.4rem] border p-5">{form.contextMode === "limited" ? <><p className="data-label text-primary">No JD Mode</p><h2 className="editorial-title mt-2 text-3xl">Email-first outreach</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">No job description was supplied. The studio only creates a factual email asking for role details; your master resume stays unchanged.</p><div className="mt-5 space-y-2"><Label htmlFor="workspace-contact">Contact email</Label><Input id="workspace-contact" type="email" value={form.contactEmail} onChange={event => setForm({ ...form, contactEmail: event.target.value })} /></div></> : <><p className="data-label text-primary">Job description</p>{form.sourceUrl && <p className="mt-2 break-all text-xs leading-5 text-muted-foreground">Imported from: {form.sourceUrl}</p>}<Textarea value={form.jobDescription} onChange={event => setForm({ ...form, jobDescription: event.target.value })} className="mt-4 min-h-[350px] leading-6" /></>}</section><section className="paper-panel rounded-[1.4rem] border p-5"><p className="data-label text-primary">Private notes</p><Textarea value={form.notes} onChange={event => setForm({ ...form, notes: event.target.value })} placeholder="Interview context, follow-up reminders, or anything useful for this application…" className="mt-4 min-h-44 leading-6" /></section></div>
  <div className="space-y-6"><section className="paper-panel rounded-[1.4rem] border p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="data-label text-primary">Tailored resume</p><h2 className="editorial-title mt-1 text-3xl">A factual, role-aware version</h2></div><ExportActions content={form.tailoredResume} kind="resume" fileStem={fileStem} company={form.company} role={form.role} /></div><Textarea value={form.tailoredResume} onChange={event => setForm({ ...form, tailoredResume: event.target.value })} placeholder="Generate a tailored resume after saving your master profile…" className="mt-5 min-h-[450px] font-mono text-[13px] leading-6" /></section><section className="paper-panel rounded-[1.4rem] border p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="data-label text-primary">Personalized cover letter</p><h2 className="editorial-title mt-1 text-3xl">Grounded and ready to refine</h2></div><ExportActions content={form.emailDraft} kind="cover-letter" fileStem={fileStem} company={form.company} role={form.role} /></div><Textarea value={form.emailDraft} onChange={event => setForm({ ...form, emailDraft: event.target.value })} placeholder="Generate a personalized draft grounded in your profile and this job description…" className="mt-5 min-h-64 leading-6" /></section></div></div></form>;
}
